### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by lolaswift** [tkssharma/e-CommerseHub#1]
I got the following error when running in containers by following your blog https://medium.com/@tkssharma/building-microservices-containers-node-js-b74f4e232ec0

xhr.js:155 GET http://ms-commerce.com/cart/v1/products 502 (Bad Gateway)
dispatchXhrRequest @ xhr.js:155
xhrAdapter @ xhr.js:16
dispatchRequest @ dispatchRequest.js:49
Promise.then (async)
request @ Axios.js:55
Axios.<computed> @ Axios.js:65
wrap @ bind.js:11
(anonymous) @ actions.js:20
(anonymous) @ index.js:8
(anonymous) @ redux.js:463
Shelf._this.handleFetchProducts @ index.js:46
componentDidMount @ index.js:26
commitLifeCycles @ react-dom.development.js:18115
commitAllLifeCycles @ react-dom.development.js:19674
callCallback @ react-dom.development.js:147
invokeGuardedCallbackDev @ react-dom.development.js:196
invokeGuardedCallback @ react-dom.development.js:250
commitRoot @ react-dom.development.js:19898
(anonymous) @ react-dom.development.js:21446
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:21445
performWorkOnRoot @ react-dom.development.js:21368
performWork @ react-dom.development.js:21273
performSyncWork @ react-dom.development.js:21247
requestWork @ react-dom.development.js:21102
scheduleWork @ react-dom.development.js:20915
scheduleRootUpdate @ react-dom.development.js:21610
updateContainerAtExpirationTime @ react-dom.development.js:21636
updateContainer @ react-dom.development.js:21704
push../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:22017
(anonymous) @ react-dom.development.js:22169
unbatchedUpdates @ react-dom.development.js:21492
legacyRenderSubtreeIntoContainer @ react-dom.development.js:22165
render @ react-dom.development.js:22240
./src/index.js @ index.js:26
__webpack_require__ @ bootstrap:781
fn @ bootstrap:149
0 @ index.js:54
__webpack_require__ @ bootstrap:781
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
Show 11 more frames
:3003/#/:1 Access to XMLHttpRequest at ‘http://ms-commerce.com/cart/v1/products' from origin ‘http://ms-commerce.com:3003' has been blocked by CORS policy: No ‘Access-Control-Allow-Origin’ header is present on the requested resource.

**Comment by tkssharma** [comment]
add CORS in response headers of your APIs
